"""initial_schema

Revision ID: c9b92c5b7451
Revises:
Create Date: 2026-08-07 23:33:51.495837

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9b92c5b7451"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_assets",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("text_malagasy", sa.Text(), nullable=False),
        sa.Column("audio_url", sa.String(length=512), nullable=False),
        sa.Column("voice_model_version", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audio_assets_text_malagasy"), "audio_assets", ["text_malagasy"], unique=False
    )
    op.create_table(
        "badges",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon_url", sa.String(length=512), nullable=True),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_language", sa.String(length=80), nullable=False),
        sa.Column("source_language", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leagues",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("week_end", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tier", "week_start", name="uq_league_tier_week"),
    )
    op.create_index(op.f("ix_leagues_tier"), "leagues", ["tier"], unique=False)
    op.create_index(op.f("ix_leagues_week_start"), "leagues", ["week_start"], unique=False)
    op.create_table(
        "publications",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "histoire", "geographie", "culture", name="publication_category", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("cover_image_url", sa.String(length=512), nullable=True),
        sa.Column("author", sa.String(length=120), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_publications_category"), "publications", ["category"], unique=False)
    op.create_index(
        op.f("ix_publications_published_at"), "publications", ["published_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "admin", name="user_role", native_enum=False), nullable=False
        ),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("xp_total", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("hearts", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "friendships",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("friend_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", name="friendship_status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["friend_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "friend_id", name="uq_friendship_pair"),
    )
    op.create_index(op.f("ix_friendships_friend_id"), "friendships", ["friend_id"], unique=False)
    op.create_index(op.f("ix_friendships_status"), "friendships", ["status"], unique=False)
    op.create_index(op.f("ix_friendships_user_id"), "friendships", ["user_id"], unique=False)
    op.create_table(
        "league_memberships",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("league_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("xp_this_week", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["league_id"], ["leagues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("league_id", "user_id", name="uq_league_user"),
    )
    op.create_index(
        op.f("ix_league_memberships_league_id"), "league_memberships", ["league_id"], unique=False
    )
    op.create_index(
        op.f("ix_league_memberships_user_id"), "league_memberships", ["user_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "streak_reminder",
                "league_result",
                "badge_earned",
                "friend_request",
                "system",
                name="notification_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_type"), "notifications", ["type"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "publication_comments",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("publication_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["publication_id"], ["publications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_publication_comments_created_at"),
        "publication_comments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publication_comments_publication_id"),
        "publication_comments",
        ["publication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publication_comments_user_id"), "publication_comments", ["user_id"], unique=False
    )
    op.create_table(
        "publication_likes",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("publication_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.ForeignKeyConstraint(["publication_id"], ["publications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publication_id", "user_id", name="uq_publication_like"),
    )
    op.create_index(
        op.f("ix_publication_likes_publication_id"),
        "publication_likes",
        ["publication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publication_likes_user_id"), "publication_likes", ["user_id"], unique=False
    )
    op.create_table(
        "units",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("course_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "order", name="uq_unit_course_order"),
    )
    op.create_index(op.f("ix_units_course_id"), "units", ["course_id"], unique=False)
    op.create_table(
        "user_badges",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("badge_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "earned_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["badge_id"], ["badges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "badge_id", name="uq_user_badge"),
    )
    op.create_index(op.f("ix_user_badges_badge_id"), "user_badges", ["badge_id"], unique=False)
    op.create_index(op.f("ix_user_badges_user_id"), "user_badges", ["user_id"], unique=False)
    op.create_table(
        "xp_transactions",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_xp_transactions_created_at"), "xp_transactions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_xp_transactions_user_id"), "xp_transactions", ["user_id"], unique=False
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("unit_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unit_id", "order", name="uq_lesson_unit_order"),
    )
    op.create_index(op.f("ix_lessons_unit_id"), "lessons", ["unit_id"], unique=False)
    op.create_table(
        "exercises",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("lesson_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "type",
            sa.Enum("mcq", "translate", "listen", "speak", name="exercise_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("correct_answer", sa.Text(), nullable=False),
        sa.Column("audio_asset_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["audio_asset_id"], ["audio_assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercises_audio_asset_id"), "exercises", ["audio_asset_id"], unique=False
    )
    op.create_index(op.f("ix_exercises_lesson_id"), "exercises", ["lesson_id"], unique=False)
    op.create_table(
        "user_progress",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("lesson_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "locked", "in_progress", "completed", name="progress_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "lesson_id", name="uq_user_lesson_progress"),
    )
    op.create_index(
        op.f("ix_user_progress_lesson_id"), "user_progress", ["lesson_id"], unique=False
    )
    op.create_index(op.f("ix_user_progress_status"), "user_progress", ["status"], unique=False)
    op.create_index(op.f("ix_user_progress_user_id"), "user_progress", ["user_id"], unique=False)
    op.create_table(
        "exercise_attempts",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("exercise_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "answered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercise_attempts_answered_at"), "exercise_attempts", ["answered_at"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_attempts_exercise_id"), "exercise_attempts", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_attempts_user_id"), "exercise_attempts", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exercise_attempts_user_id"), table_name="exercise_attempts")
    op.drop_index(op.f("ix_exercise_attempts_exercise_id"), table_name="exercise_attempts")
    op.drop_index(op.f("ix_exercise_attempts_answered_at"), table_name="exercise_attempts")
    op.drop_table("exercise_attempts")
    op.drop_index(op.f("ix_user_progress_user_id"), table_name="user_progress")
    op.drop_index(op.f("ix_user_progress_status"), table_name="user_progress")
    op.drop_index(op.f("ix_user_progress_lesson_id"), table_name="user_progress")
    op.drop_table("user_progress")
    op.drop_index(op.f("ix_exercises_lesson_id"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_audio_asset_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_lessons_unit_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_xp_transactions_user_id"), table_name="xp_transactions")
    op.drop_index(op.f("ix_xp_transactions_created_at"), table_name="xp_transactions")
    op.drop_table("xp_transactions")
    op.drop_index(op.f("ix_user_badges_user_id"), table_name="user_badges")
    op.drop_index(op.f("ix_user_badges_badge_id"), table_name="user_badges")
    op.drop_table("user_badges")
    op.drop_index(op.f("ix_units_course_id"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_publication_likes_user_id"), table_name="publication_likes")
    op.drop_index(op.f("ix_publication_likes_publication_id"), table_name="publication_likes")
    op.drop_table("publication_likes")
    op.drop_index(op.f("ix_publication_comments_user_id"), table_name="publication_comments")
    op.drop_index(op.f("ix_publication_comments_publication_id"), table_name="publication_comments")
    op.drop_index(op.f("ix_publication_comments_created_at"), table_name="publication_comments")
    op.drop_table("publication_comments")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_league_memberships_user_id"), table_name="league_memberships")
    op.drop_index(op.f("ix_league_memberships_league_id"), table_name="league_memberships")
    op.drop_table("league_memberships")
    op.drop_index(op.f("ix_friendships_user_id"), table_name="friendships")
    op.drop_index(op.f("ix_friendships_status"), table_name="friendships")
    op.drop_index(op.f("ix_friendships_friend_id"), table_name="friendships")
    op.drop_table("friendships")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_publications_published_at"), table_name="publications")
    op.drop_index(op.f("ix_publications_category"), table_name="publications")
    op.drop_table("publications")
    op.drop_index(op.f("ix_leagues_week_start"), table_name="leagues")
    op.drop_index(op.f("ix_leagues_tier"), table_name="leagues")
    op.drop_table("leagues")
    op.drop_table("courses")
    op.drop_table("badges")
    op.drop_index(op.f("ix_audio_assets_text_malagasy"), table_name="audio_assets")
    op.drop_table("audio_assets")
    # ### end Alembic commands ###
